import { GRINDER_TYPICAL_USES, GRINDER_UNIT_TYPES } from '@brewmate/shared';

import { estimatedCalibration } from './estimatedCalibration.js';
import type { GrinderSeed } from './grinderSeed.js';

/**
 * The long tail: every grinder a published grind-size chart covers that the
 * four hand-written lists above do not.
 *
 * Why it exists. The four lists are the grinders somebody sat down and wrote
 * out, which means they are the grinders somebody thought of - and the one
 * moment this app has to be right is the moment a person opens the picker
 * looking for whatever they actually bought. A cheap household grinder nobody
 * would put in a curated list is exactly the one whose owner has no idea where
 * to start, and "not in the catalogue" is the answer that sends them away.
 *
 * Where the numbers come from, and what each of them is worth:
 *
 * - `minSetting`, `maxSetting` and `step` are the collar as the manufacturer
 *   marks it. `step` is the finest detent the scale admits, so a grinder
 *   counted in tenths of a rotation records 0.1 rather than 1.
 * - `micronCalibration` is **derived, not copied**. The source charts publish
 *   which part of each collar each brewing method lives on; this file fits a
 *   straight line through those positions against Brewmate's own micron
 *   windows (`GRIND_MICRON_WINDOWS`) and takes three points off it. The fitted
 *   slope reproduces the separately published microns-per-step figure for these
 *   grinders to within a few percent, which is the only reason it is shipped at
 *   all - two unrelated derivations agreeing is evidence, one derivation is a
 *   guess with more steps.
 * - A straight line, and only three points, because the evidence is a handful
 *   of wide ranges. A spline through six approximate positions would be a more
 *   elaborate way of being equally wrong, and it would read as precision this
 *   data has not earned.
 * - Every curve here is `isEstimated`, which the app prints beside the number.
 * - Where a chart covers too few brewing methods to fit anything, the entry
 *   ships with no curve at all. The grinder is still in the picker, still
 *   searchable, and still gets a grind in words - an invented curve would be
 *   worse than none.
 *
 * Entries already covered by the hand-written lists are deliberately absent:
 * the seed is matched on brand and model, and two rows for one grinder would be
 * two answers to the same question.
 */
export const CHART_GRINDER_SEEDS: readonly GrinderSeed[] = [
  {
    brand: '1Zpresso',
    model: 'J',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.667,
    maxSetting: 40,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 2.82, microns: 80 },
      { setting: 21.41, microns: 634 },
      { setting: 40, microns: 1187 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'J-Max S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.6,
    maxSetting: 45,
    step: 0.1,
    micronCalibration: estimatedCalibration([
      { setting: 1.6, microns: 89 },
      { setting: 23.3, microns: 659 },
      { setting: 45, microns: 1228 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'JE',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 2.333,
    maxSetting: 50,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 8.62, microns: 80 },
      { setting: 29.31, microns: 578 },
      { setting: 50, microns: 1075 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'JX S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.667,
    maxSetting: 40,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 2.82, microns: 80 },
      { setting: 21.41, microns: 634 },
      { setting: 40, microns: 1187 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'JX-Pro S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 2.25,
    maxSetting: 50,
    step: 0.25,
    micronCalibration: estimatedCalibration([
      { setting: 7.63, microns: 80 },
      { setting: 28.81, microns: 592 },
      { setting: 50, microns: 1103 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'K-Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.5,
    maxSetting: 17.4,
    step: 0.1,
    micronCalibration: estimatedCalibration([
      { setting: 0.5, microns: 141 },
      { setting: 8.95, microns: 729 },
      { setting: 17.4, microns: 1317 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'Q Air',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.1,
    maxSetting: 40,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 1.1, microns: 138 },
      { setting: 20.55, microns: 720 },
      { setting: 40, microns: 1301 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'Q2 (Heptagonal burrs)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.1,
    maxSetting: 40,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 1.1, microns: 138 },
      { setting: 20.55, microns: 720 },
      { setting: 40, microns: 1301 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'Q2 (Pentagonal burrs)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.1,
    maxSetting: 40,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 1.1, microns: 138 },
      { setting: 20.55, microns: 720 },
      { setting: 40, microns: 1301 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'Q2 S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.1,
    maxSetting: 40,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 1.1, microns: 138 },
      { setting: 20.55, microns: 720 },
      { setting: 40, microns: 1301 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'X-Pro S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.8,
    maxSetting: 24,
    step: 0.1,
    micronCalibration: estimatedCalibration([
      { setting: 0.8, microns: 109 },
      { setting: 12.4, microns: 675 },
      { setting: 24, microns: 1242 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'X-Ultra',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.8,
    maxSetting: 24,
    step: 0.1,
    micronCalibration: estimatedCalibration([
      { setting: 0.8, microns: 97 },
      { setting: 12.4, microns: 665 },
      { setting: 24, microns: 1234 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'ZP6 Special',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 9,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 234 },
      { setting: 4.5, microns: 709 },
      { setting: 9, microns: 1183 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Acaia',
    model: 'Orbit',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.6,
    maxSetting: 18.7,
    step: 0.1,
    micronCalibration: estimatedCalibration([
      { setting: 0.6, microns: 144 },
      { setting: 9.65, microns: 730 },
      { setting: 18.7, microns: 1316 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Anfim',
    model: 'Best',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 28,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 270 },
      { setting: 14, microns: 794 },
      { setting: 28, microns: 1318 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Anfim',
    model: 'SP II',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 14,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Balmuda',
    model: 'Coffee Mill',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 23,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 186 },
      { setting: 12, microns: 739 },
      { setting: 23, microns: 1291 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Encore ESP Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 11.25, microns: 80 },
      { setting: 35.63, microns: 559 },
      { setting: 60, microns: 1037 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Forté AP',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 10.962,
    step: 0.038,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 253 },
      { setting: 5.98, microns: 737 },
      { setting: 10.96, microns: 1221 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Forté BG',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 10.962,
    step: 0.038,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 253 },
      { setting: 5.98, microns: 737 },
      { setting: 10.96, microns: 1221 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Maestro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 194 },
      { setting: 20.5, microns: 674 },
      { setting: 40, microns: 1154 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Maestro Plus',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 194 },
      { setting: 20.5, microns: 674 },
      { setting: 40, microns: 1154 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Preciso',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40.909,
    step: 0.091,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 235 },
      { setting: 20.95, microns: 730 },
      { setting: 40.91, microns: 1224 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Sette 270 W',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 31,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 200 },
      { setting: 16, microns: 663 },
      { setting: 31, microns: 1125 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Sette 270 Wi',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 31,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 200 },
      { setting: 16, microns: 663 },
      { setting: 31, microns: 1125 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Sette 30',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 31,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 200 },
      { setting: 16, microns: 663 },
      { setting: 31, microns: 1125 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Starbucks Barista',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 194 },
      { setting: 20.5, microns: 674 },
      { setting: 40, microns: 1154 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Vario W',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 10.957,
    step: 0.043,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 253 },
      { setting: 5.98, microns: 737 },
      { setting: 10.96, microns: 1222 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Vario W+',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 10.955,
    step: 0.045,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 254 },
      { setting: 5.98, microns: 738 },
      { setting: 10.96, microns: 1222 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Virtuoso',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 40,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 214 },
      { setting: 20, microns: 705 },
      { setting: 40, microns: 1195 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Barista & Co',
    model: 'Core All Grind',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 40,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 203 },
      { setting: 20, microns: 677 },
      { setting: 40, microns: 1150 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Barista Space',
    model: 'Premium Coffee Hand Grinder',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 48,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 2.22, microns: 80 },
      { setting: 25.11, microns: 640 },
      { setting: 48, microns: 1200 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'BelleLife',
    model: 'Electric Coffee Grinder',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 49,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 293 },
      { setting: 25, microns: 806 },
      { setting: 49, microns: 1319 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Bentwood',
    model: 'Vertical 63',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 40,
    maxSetting: 1400,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 40, microns: 142 },
      { setting: 720, microns: 729 },
      { setting: 1400, microns: 1317 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Bodum',
    model: 'Bistro 10903',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 12,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 403 },
      { setting: 6.5, microns: 852 },
      { setting: 12, microns: 1301 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Bravo',
    model: 'IT',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.6,
    maxSetting: 18.6,
    step: 0.1,
    micronCalibration: estimatedCalibration([
      { setting: 0.6, microns: 147 },
      { setting: 9.6, microns: 732 },
      { setting: 18.6, microns: 1316 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Cafflano',
    model: 'Grinder',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 2,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 2.33, microns: 80 },
      { setting: 9.16, microns: 594 },
      { setting: 16, microns: 1108 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Capresso',
    model: 'Infinity',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 279 },
      { setting: 8.5, microns: 757 },
      { setting: 16, microns: 1236 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Capresso',
    model: 'Infinity Plus',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 279 },
      { setting: 8.5, microns: 757 },
      { setting: 16, microns: 1236 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Comandante',
    model: 'C40 MK4 (with Red Clix)',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 3,
    maxSetting: 80,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 5.46, microns: 80 },
      { setting: 42.73, microns: 635 },
      { setting: 80, microns: 1189 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Comandante',
    model: 'C60 Baracuda',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 3,
    maxSetting: 55,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4.1, microns: 80 },
      { setting: 29.55, microns: 635 },
      { setting: 55, microns: 1190 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Comandante',
    model: 'C60 Baracuda (with Gold Clix)',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 5,
    maxSetting: 110,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 7.44, microns: 80 },
      { setting: 58.72, microns: 636 },
      { setting: 110, microns: 1191 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Comandante',
    model: 'X25 Trailmaster',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 40,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 2.36, microns: 80 },
      { setting: 21.18, microns: 628 },
      { setting: 40, microns: 1176 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Comandante',
    model: 'X25 Trailmaster (with Red Clix)',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 3,
    maxSetting: 80,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 5.46, microns: 80 },
      { setting: 42.73, microns: 635 },
      { setting: 80, microns: 1189 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Compak',
    model: 'K3 Push',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 327 },
      { setting: 15, microns: 788 },
      { setting: 30, microns: 1250 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Compak',
    model: 'K3 Touch',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 327 },
      { setting: 15, microns: 788 },
      { setting: 30, microns: 1250 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Compak',
    model: 'K3 Touch Advanced',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 327 },
      { setting: 15, microns: 788 },
      { setting: 30, microns: 1250 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Cores',
    model: 'Cone Grinder C330',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 9.5,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 368 },
      { setting: 5.25, microns: 852 },
      { setting: 9.5, microns: 1336 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Cuisinart',
    model: 'CBM-18',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 13,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 516 },
      { setting: 7, microns: 888 },
      { setting: 13, microns: 1259 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Cuisinart',
    model: 'DBM-8',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 12,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 506 },
      { setting: 6.5, microns: 878 },
      { setting: 12, microns: 1250 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: "De'Longhi",
    model: 'KG79',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 380 },
      { setting: 8, microns: 822 },
      { setting: 16, microns: 1263 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: "De'Longhi",
    model: 'KG89',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 380 },
      { setting: 8, microns: 822 },
      { setting: 16, microns: 1263 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Epeios',
    model: 'Essense Go',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 77,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 310 },
      { setting: 38.5, microns: 817 },
      { setting: 77, microns: 1323 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Etzinger',
    model: 'etz-I (Regular)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 23,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 207 },
      { setting: 12, microns: 713 },
      { setting: 23, microns: 1219 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Etzinger',
    model: 'etz-I (Trim)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 23,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 207 },
      { setting: 12, microns: 713 },
      { setting: 23, microns: 1219 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Etzinger',
    model: 'etz-U',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 23,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 207 },
      { setting: 12, microns: 713 },
      { setting: 23, microns: 1219 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Eureka',
    model: 'Atom 60',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 255 },
      { setting: 15, microns: 784 },
      { setting: 30, microns: 1312 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Eureka',
    model: 'Atom 75',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 255 },
      { setting: 15, microns: 784 },
      { setting: 30, microns: 1312 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Eureka',
    model: 'Drogheria MCD4',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 8,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.17, microns: 80 },
      { setting: 4.09, microns: 578 },
      { setting: 8, microns: 1075 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Classico',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 12,
    step: 0.5,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 268 },
      { setting: 6, microns: 785 },
      { setting: 12, microns: 1302 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Oro XL',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 166 },
      { setting: 15, microns: 644 },
      { setting: 30, microns: 1123 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Specialità',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 24,
    step: 0.5,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 271 },
      { setting: 12, microns: 791 },
      { setting: 24, microns: 1311 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Fellow',
    model: 'Ode Brew Grinder Gen 1',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 11,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 538 },
      { setting: 6, microns: 944 },
      { setting: 11, microns: 1350 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Fellow',
    model: 'Ode Brew Grinder Gen 2',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 11,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 321 },
      { setting: 6, microns: 765 },
      { setting: 11, microns: 1210 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Fiorenzato',
    model: 'Pietro (B-Modal Burrs)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 10,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 122 },
      { setting: 5, microns: 614 },
      { setting: 10, microns: 1105 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Fiorenzato',
    model: 'Pietro (M-Modal Burrs)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 10,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 201 },
      { setting: 5, microns: 675 },
      { setting: 10, microns: 1149 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Fiorenzato (Sanremo)',
    model: 'Allground',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 73,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 5.75, microns: 80 },
      { setting: 39.37, microns: 534 },
      { setting: 73, microns: 987 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Fiorenzato (Sanremo)',
    model: 'Allground Sense',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 73,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 5.75, microns: 80 },
      { setting: 39.37, microns: 534 },
      { setting: 73, microns: 987 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Flair Espresso',
    model: 'Royal Grinder',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 35,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 144 },
      { setting: 18, microns: 728 },
      { setting: 35, microns: 1313 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Fuji Royal',
    model: 'R-220',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 10,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 284 },
      { setting: 5.5, microns: 744 },
      { setting: 10, microns: 1203 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Goat Story',
    model: 'Arco',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 7,
    maxSetting: 233,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 7, microns: 146 },
      { setting: 120, microns: 731 },
      { setting: 233, microns: 1315 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Handground',
    model: 'Precision Coffee Grinder',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 6,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 375 },
      { setting: 3, microns: 855 },
      { setting: 6, microns: 1335 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hario',
    model: 'Mini Mill PLUS',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 20,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 285 },
      { setting: 10.5, microns: 796 },
      { setting: 20, microns: 1307 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hario',
    model: 'Mini Mill Slim PRO',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 20,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 285 },
      { setting: 10.5, microns: 796 },
      { setting: 20, microns: 1307 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hario',
    model: 'Skerton',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 9,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 384 },
      { setting: 5, microns: 840 },
      { setting: 9, microns: 1297 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hario',
    model: 'Skerton PLUS',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 9,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 384 },
      { setting: 5, microns: 840 },
      { setting: 9, microns: 1297 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hario',
    model: 'Smart-G',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 14,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 319 },
      { setting: 7.5, microns: 807 },
      { setting: 14, microns: 1295 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hario',
    model: 'V60 EVC-8B',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 10,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 207 },
      { setting: 5, microns: 725 },
      { setting: 10, microns: 1243 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hario',
    model: 'V60 EVCG-8B-E',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 44,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 260 },
      { setting: 22.5, microns: 687 },
      { setting: 44, microns: 1113 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Helor',
    model: '101',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 3,
    maxSetting: 80,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3, microns: 153 },
      { setting: 41.5, microns: 734 },
      { setting: 80, microns: 1314 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Helor',
    model: '106 Flux',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 33.8,
    step: 0.2,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 144 },
      { setting: 17.4, microns: 730 },
      { setting: 33.8, microns: 1316 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'HeyCafé',
    model: 'H1',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 8,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.09, microns: 79 },
      { setting: 4.05, microns: 628 },
      { setting: 8, microns: 1176 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'HiBREW',
    model: 'G4B',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 5,
    maxSetting: 55,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hongbei',
    model: 'Coffee Grinder',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 32,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 137 },
      { setting: 16.5, microns: 726 },
      { setting: 32, microns: 1316 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'JavaPresse',
    model: 'Manual Coffee Grinder',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 20,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 245 },
      { setting: 10.5, microns: 777 },
      { setting: 20, microns: 1309 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Joy Resolve',
    model: 'Groove Compact',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 39,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 293 },
      { setting: 19.5, microns: 804 },
      { setting: 39, microns: 1316 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kaldi',
    model: 'Ceramic Coffee Mill',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.1,
    maxSetting: 1.2,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.1, microns: 279 },
      { setting: 0.65, microns: 819 },
      { setting: 1.2, microns: 1360 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kalita',
    model: 'C-90',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 8,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 520 },
      { setting: 4.5, microns: 870 },
      { setting: 8, microns: 1220 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Kalita',
    model: 'DIA Coffee Mill',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 1.25,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.02, microns: 81 },
      { setting: 0.63, microns: 693 },
      { setting: 1.25, microns: 1315 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kalita',
    model: 'Next G',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 11,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 521 },
      { setting: 6, microns: 898 },
      { setting: 11, microns: 1275 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Kalita',
    model: 'Nice Cut G',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 6,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 521 },
      { setting: 3.5, microns: 898 },
      { setting: 6, microns: 1275 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Kanso',
    model: 'Hiku',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.15,
    maxSetting: 2.2,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.39, microns: 81 },
      { setting: 1.29, microns: 570 },
      { setting: 2.2, microns: 1064 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'K0',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 6,
    maxSetting: 140,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 13.04, microns: 80 },
      { setting: 76.52, microns: 623 },
      { setting: 140, microns: 1166 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'K3',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 6,
    maxSetting: 140,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 13.04, microns: 80 },
      { setting: 76.52, microns: 623 },
      { setting: 140, microns: 1166 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'K5',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 6,
    maxSetting: 140,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 13.04, microns: 80 },
      { setting: 76.52, microns: 623 },
      { setting: 140, microns: 1166 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'P0',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 4,
    maxSetting: 130,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4, microns: 145 },
      { setting: 67, microns: 729 },
      { setting: 130, microns: 1314 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'P1',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 4,
    maxSetting: 130,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4, microns: 145 },
      { setting: 67, microns: 729 },
      { setting: 130, microns: 1314 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kinu',
    model: 'M47 Classic',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.3,
    maxSetting: 8.5,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.3, microns: 147 },
      { setting: 4.4, microns: 734 },
      { setting: 8.5, microns: 1320 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kinu',
    model: 'M47 Phoenix',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.3,
    maxSetting: 8.5,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.3, microns: 147 },
      { setting: 4.4, microns: 734 },
      { setting: 8.5, microns: 1320 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kinu',
    model: 'M47 Simplicity',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.3,
    maxSetting: 8.5,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.3, microns: 147 },
      { setting: 4.4, microns: 734 },
      { setting: 8.5, microns: 1320 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kinu',
    model: 'M47 Traveller',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.3,
    maxSetting: 8.5,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.3, microns: 147 },
      { setting: 4.4, microns: 734 },
      { setting: 8.5, microns: 1320 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'KitchenAid',
    model: 'Artisan Coffee Grinder 5KCG0702',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 8,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 1157 },
      { setting: 4.5, microns: 729 },
      { setting: 8, microns: 301 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'KitchenAid',
    model: 'Coffee Grinder 5KCG8433',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 70,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 1213 },
      { setting: 35.5, microns: 736 },
      { setting: 70, microns: 258 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Knock',
    model: 'Feld2',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.2,
    maxSetting: 5,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.2, microns: 109 },
      { setting: 2.6, microns: 738 },
      { setting: 5, microns: 1368 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Knock',
    model: 'Feld47',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 2,
    maxSetting: 62,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 2, microns: 147 },
      { setting: 32, microns: 732 },
      { setting: 62, microns: 1316 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Krups',
    model: 'GVX1',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 17,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 321 },
      { setting: 9, microns: 736 },
      { setting: 17, microns: 1151 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Krups',
    model: 'GX5000',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 12,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 403 },
      { setting: 6.5, microns: 852 },
      { setting: 12, microns: 1301 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Krups',
    model: 'GX6000',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 503 },
      { setting: 8.5, microns: 881 },
      { setting: 16, microns: 1259 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Mahlkönig',
    model: 'EK43 (0-16)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 110 },
      { setting: 8, microns: 568 },
      { setting: 16, microns: 1025 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mahlkönig',
    model: 'EK43 (1-11)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 11,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 108 },
      { setting: 6, microns: 567 },
      { setting: 11, microns: 1025 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mahlkönig',
    model: 'GH2 (HC880)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 17,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 106 },
      { setting: 8.5, microns: 651 },
      { setting: 17, microns: 1196 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mahlkönig',
    model: 'VTA 6S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 13,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 122 },
      { setting: 7, microns: 625 },
      { setting: 13, microns: 1129 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mahlkönig',
    model: 'VTA 6S W',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 13,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 122 },
      { setting: 7, microns: 625 },
      { setting: 13, microns: 1129 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mavo',
    model: 'Phantox Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.4,
    maxSetting: 12,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.4, microns: 91 },
      { setting: 6.2, microns: 661 },
      { setting: 12, microns: 1231 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mazzer',
    model: 'ZM',
    unitType: GRINDER_UNIT_TYPES.microns,
    minSetting: 40,
    maxSetting: 1400,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 40, microns: 40 },
      { setting: 1400, microns: 1400 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mazzer',
    model: 'ZM Plus',
    unitType: GRINDER_UNIT_TYPES.microns,
    minSetting: 40,
    maxSetting: 1400,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 40, microns: 40 },
      { setting: 1400, microns: 1400 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Melitta',
    model: 'Calibra',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 37,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 475 },
      { setting: 19, microns: 874 },
      { setting: 37, microns: 1273 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Melitta',
    model: 'Molino',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 17,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 254 },
      { setting: 9, microns: 717 },
      { setting: 17, microns: 1180 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'MHW-3BOMBER',
    model: 'Blade R3',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 36,
    step: 0.2,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 210 },
      { setting: 18, microns: 716 },
      { setting: 36, microns: 1223 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'MiiCoffee',
    model: 'D40+',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 8,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.14, microns: 80 },
      { setting: 4.07, microns: 610 },
      { setting: 8, microns: 1140 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Moccamaster',
    model: 'KM5',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 9,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 515 },
      { setting: 5, microns: 844 },
      { setting: 9, microns: 1173 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'montwave',
    model: 'GU2',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 28,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 152 },
      { setting: 14.5, microns: 731 },
      { setting: 28, microns: 1311 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mueller',
    model: 'Ultra-Grind',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 7.4,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 511 },
      { setting: 4.2, microns: 908 },
      { setting: 7.4, microns: 1305 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Option-O',
    model: 'Lagom Casa',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0.9,
    maxSetting: 29.5,
    step: 0.1,
    micronCalibration: estimatedCalibration([
      { setting: 0.9, microns: 144 },
      { setting: 15.2, microns: 730 },
      { setting: 29.5, microns: 1317 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Option-O',
    model: 'Lagom Mini (Moonshine burrs)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 4,
    maxSetting: 140,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4, microns: 142 },
      { setting: 72, microns: 729 },
      { setting: 140, microns: 1317 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Option-O',
    model: 'Lagom Mini (Obsidian burrs)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 6,
    maxSetting: 198,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 6, microns: 144 },
      { setting: 102, microns: 730 },
      { setting: 198, microns: 1316 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Orphan Espresso',
    model: 'Lido OG',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 40,
    maxSetting: 1400,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 40, microns: 142 },
      { setting: 720, microns: 729 },
      { setting: 1400, microns: 1317 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'OXO',
    model: 'Conical Burr Coffee Grinder',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 15,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 245 },
      { setting: 8, microns: 726 },
      { setting: 15, microns: 1206 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Pinecone',
    model: 'Pinion',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 365 },
      { setting: 18, microns: 847 },
      { setting: 36, microns: 1329 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Porlex',
    model: 'Mini II',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 24,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 144 },
      { setting: 12.5, microns: 731 },
      { setting: 24, microns: 1318 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Porlex',
    model: 'Tall II',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 24,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 144 },
      { setting: 12.5, microns: 731 },
      { setting: 24, microns: 1318 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Precision',
    model: 'GS30',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 14,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 299 },
      { setting: 7, microns: 810 },
      { setting: 14, microns: 1321 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Rancilio',
    model: 'Rocky SD',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 55,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 216 },
      { setting: 27.5, microns: 708 },
      { setting: 55, microns: 1199 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'ROK',
    model: 'GrinderGC',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 1,
    maxSetting: 25,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 192 },
      { setting: 13, microns: 672 },
      { setting: 25, microns: 1151 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Saint Anthony Industries',
    model: 'Millwright Hand Grinder',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 3,
    maxSetting: 98,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3, microns: 146 },
      { setting: 50.5, microns: 729 },
      { setting: 98, microns: 1313 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Smeg',
    model: 'CGF01',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 277 },
      { setting: 15, microns: 746 },
      { setting: 30, microns: 1214 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Smeg',
    model: 'CGF11',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 277 },
      { setting: 15, microns: 746 },
      { setting: 30, microns: 1214 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C2',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4.01, microns: 80 },
      { setting: 17.01, microns: 599 },
      { setting: 30, microns: 1118 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C2 Fold',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4.01, microns: 80 },
      { setting: 17.01, microns: 599 },
      { setting: 30, microns: 1118 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C2 Max',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4.01, microns: 80 },
      { setting: 17.01, microns: 599 },
      { setting: 30, microns: 1118 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C2 Max Pro',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4.01, microns: 80 },
      { setting: 17.01, microns: 599 },
      { setting: 30, microns: 1118 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 25,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3.04, microns: 80 },
      { setting: 14.02, microns: 592 },
      { setting: 25, microns: 1104 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3 ESP',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.333,
    maxSetting: 30,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 3.04, microns: 80 },
      { setting: 16.52, microns: 616 },
      { setting: 30, microns: 1152 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3 ESP Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1.333,
    maxSetting: 30,
    step: 0.333,
    micronCalibration: estimatedCalibration([
      { setting: 3.04, microns: 80 },
      { setting: 16.52, microns: 616 },
      { setting: 30, microns: 1152 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3 Max',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 25,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3.04, microns: 80 },
      { setting: 14.02, microns: 592 },
      { setting: 25, microns: 1104 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3 Max Pro',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 25,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3.04, microns: 80 },
      { setting: 14.02, microns: 592 },
      { setting: 25, microns: 1104 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3 Pro',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 25,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3.04, microns: 80 },
      { setting: 14.02, microns: 592 },
      { setting: 25, microns: 1104 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3S',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 25,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3.04, microns: 80 },
      { setting: 14.02, microns: 592 },
      { setting: 25, microns: 1104 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3S Pro',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 25,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3.04, microns: 80 },
      { setting: 14.02, microns: 592 },
      { setting: 25, microns: 1104 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'C5 ESP Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 30,
    step: 0.2,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 114 },
      { setting: 15.5, microns: 679 },
      { setting: 30, microns: 1244 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'C5 Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 2.06, microns: 80 },
      { setting: 9.03, microns: 608 },
      { setting: 16, microns: 1137 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut X',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 24,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0.97, microns: 80 },
      { setting: 12.48, microns: 610 },
      { setting: 24, microns: 1140 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'G1',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 28,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 2.56, microns: 80 },
      { setting: 15.28, microns: 619 },
      { setting: 28, microns: 1158 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'G1 Plus',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 28,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 2.56, microns: 80 },
      { setting: 15.28, microns: 619 },
      { setting: 28, microns: 1158 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Nano',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 2,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 5.31, microns: 80 },
      { setting: 17.65, microns: 551 },
      { setting: 30, microns: 1022 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'S3',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 9,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 324 },
      { setting: 4.5, microns: 771 },
      { setting: 9, microns: 1219 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Sculptor 064S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 16,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 223 },
      { setting: 8, microns: 701 },
      { setting: 16, microns: 1179 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Slim',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 2,
    maxSetting: 30,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 4.01, microns: 80 },
      { setting: 17.01, microns: 599 },
      { setting: 30, microns: 1118 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore x Millab',
    model: 'E01',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 19.2,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 177 },
      { setting: 9.6, microns: 642 },
      { setting: 19.2, microns: 1108 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore x Millab',
    model: 'M01',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 10,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 223 },
      { setting: 5, microns: 767 },
      { setting: 10, microns: 1311 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'CF64V',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 2.08, microns: 80 },
      { setting: 46.04, microns: 577 },
      { setting: 90, microns: 1073 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF54',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3.28, microns: 80 },
      { setting: 46.64, microns: 584 },
      { setting: 90, microns: 1089 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF64 (Gen 1)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 202 },
      { setting: 45, microns: 715 },
      { setting: 90, microns: 1227 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF64 (Gen 2)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 189 },
      { setting: 45, microns: 680 },
      { setting: 90, microns: 1171 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF64V',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 81 },
      { setting: 45, microns: 616 },
      { setting: 90, microns: 1151 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF83V',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 166 },
      { setting: 45, microns: 688 },
      { setting: 90, microns: 1210 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'SD40 V1',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 19,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1.43, microns: 80 },
      { setting: 10.22, microns: 614 },
      { setting: 19, microns: 1147 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'SD40 V2',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 19,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1.43, microns: 80 },
      { setting: 10.22, microns: 614 },
      { setting: 19, microns: 1147 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Varia',
    model: 'Evo Hybrid',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 144,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 5.45, microns: 80 },
      { setting: 74.72, microns: 563 },
      { setting: 144, microns: 1045 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Varia',
    model: 'Hand grinder',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 3,
    maxSetting: 83,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 3, microns: 154 },
      { setting: 43, microns: 733 },
      { setting: 83, microns: 1312 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Varia',
    model: 'VS3 (Gen 1)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 19.6,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 254 },
      { setting: 9.8, microns: 785 },
      { setting: 19.6, microns: 1315 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Varia',
    model: 'VS3 (Gen 2)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 19.6,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 254 },
      { setting: 9.8, microns: 785 },
      { setting: 19.6, microns: 1315 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Vevok Chef',
    model: '06',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 6,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 545 },
      { setting: 3.5, microns: 841 },
      { setting: 6, microns: 1137 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Vevok Chef',
    model: '06 Slim',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 6,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 545 },
      { setting: 3.5, microns: 841 },
      { setting: 6, microns: 1137 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'VSSL',
    model: 'JAVA',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 49,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 393 },
      { setting: 24.5, microns: 862 },
      { setting: 49, microns: 1332 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Wacaco',
    model: 'Exagrind',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 108 },
      { setting: 30, microns: 615 },
      { setting: 60, microns: 1122 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Weber Workshops',
    model: 'KEY Mk1',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 2,
    maxSetting: 45,
    step: 0.2,
    micronCalibration: estimatedCalibration([
      { setting: 6.13, microns: 80 },
      { setting: 25.57, microns: 599 },
      { setting: 45, microns: 1117 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Wilfa',
    model: 'Balance',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 31,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 358 },
      { setting: 16, microns: 799 },
      { setting: 31, microns: 1240 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Wilfa',
    model: 'Svart Aroma',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 18,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 325 },
      { setting: 9.5, microns: 756 },
      { setting: 18, microns: 1187 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'xBloom',
    model: 'Studio',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 80,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 185 },
      { setting: 40, microns: 678 },
      { setting: 80, microns: 1171 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Zerno',
    model: 'Z1',
    unitType: GRINDER_UNIT_TYPES.microns,
    minSetting: 40,
    maxSetting: 1400,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 40, microns: 40 },
      { setting: 1400, microns: 1400 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Zwilling',
    model: 'Enfinigy Coffee Grinder',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 140,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 223 },
      { setting: 70, microns: 703 },
      { setting: 140, microns: 1182 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
];
