import { GRINDER_TYPICAL_USES, GRINDER_UNIT_TYPES } from '@brewmate/shared';

import type { GrinderSeed } from './grinderSeed.js';

/**
 * Espresso grinders, and the single-dose machines that also do filter.
 *
 * Most of them are stepless, which is recorded as a step of zero: the collar
 * carries numbers to remember a position by, not detents to count. None of
 * them come with a published micron figure, so none is claimed.
 */
export const ESPRESSO_GRINDER_SEEDS: readonly GrinderSeed[] = [
  {
    brand: 'Eureka',
    model: 'Mignon Specialita',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Silenzio',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Zero',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Notte',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Oro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Niche',
    model: 'Zero',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Niche',
    model: 'Duo',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'DF',
    model: 'DF54',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'DF',
    model: 'DF64',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'DF',
    model: 'DF64 Gen 2',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'DF',
    model: 'DF64P',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'DF',
    model: 'DF83',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    /** The same machines under the badge they are sold with in Europe. */
    brand: 'Turin',
    model: 'DF64',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF64E',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF83',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Solo',
    model: 'Solo Grinder (DF64)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Mazzer',
    model: 'Mini',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Mazzer',
    model: 'Super Jolly',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Mazzer',
    model: 'Philos',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    brand: 'Rancilio',
    model: 'Rocky',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 55,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    /** One machine, two badges - searching for either has to find it. */
    brand: 'Sage / Breville',
    model: 'Smart Grinder Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Sage / Breville',
    model: 'Dose Control Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Weber Workshops',
    model: 'Key',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Weber Workshops',
    model: 'EG-1',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Option-O',
    model: 'Lagom Mini',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Option-O',
    model: 'Lagom P64',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Option-O',
    model: 'Lagom P100',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Ceado',
    model: 'E37S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Ceado',
    model: 'E37Z',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Ceado',
    model: 'Life',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    brand: 'Compak',
    model: 'E5',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Compak',
    model: 'E8',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Compak',
    model: 'K10',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    brand: 'Lelit',
    model: 'William PL72',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Lelit',
    model: 'Fred PL043MMI',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
];
