import { BREW_METHOD_CATEGORIES, GRINDER_TYPICAL_USES, GRINDER_UNIT_TYPES } from '@brewmate/shared';

import { estimatedCalibration } from './estimatedCalibration.js';
import type { GrinderSeed } from './grinderSeed.js';

/**
 * Espresso grinders, and the single-dose machines that also do filter.
 *
 * Most of them are stepless, which is recorded as a step of zero: the collar
 * carries numbers to remember a position by, not detents to count. None of
 * them comes with a published micron figure. *
 * A handful of them now carry a curve after all. It is not a manufacturer
 * figure and does not pretend to be: it is fitted from where a published
 * grind-size chart puts each brewing method on that exact collar, the same way
 * `chartGrinderSeeds.ts` does it and only for the entries whose collar the
 * chart describes identically. Flagged as an estimate, like every other curve
 * here. A grind with a number and a click size beats a grind with neither, as
 * long as the app keeps saying which it is holding.
 */
export const ESPRESSO_GRINDER_SEEDS: readonly GrinderSeed[] = [
  {
    brand: 'Eureka',
    model: 'Mignon Specialita',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Zero',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Eureka',
    model: 'Mignon Notte',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    brand: 'DF',
    model: 'DF54',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'DF',
    model: 'DF64',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'DF',
    model: 'DF64 Gen 2',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'DF',
    model: 'DF64P',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'DF',
    model: 'DF83',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    /** The same machines under the badge they are sold with in Europe. */
    brand: 'Turin',
    model: 'DF64',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF64E',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Turin',
    model: 'DF83',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: estimatedCalibration([
      { setting: 1.43, microns: 80 },
      { setting: 45.71, microns: 601 },
      { setting: 90, microns: 1121 },
    ]),
    settingRanges: {
      [BREW_METHOD_CATEGORIES.espresso]: { min: 8, max: 28 },
      [BREW_METHOD_CATEGORIES.stovetop]: { min: 27, max: 58 },
      [BREW_METHOD_CATEGORIES.pourOver]: { min: 32, max: 63 },
      [BREW_METHOD_CATEGORIES.batch]: { min: 21, max: 84 },
      [BREW_METHOD_CATEGORIES.immersion]: { min: 63, max: 90 },
      [BREW_METHOD_CATEGORIES.cold]: { min: 74, max: 90 },
    },
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Solo',
    model: 'Solo Grinder (DF64)',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Mazzer',
    model: 'Mini',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Mazzer',
    model: 'Super Jolly',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Mazzer',
    model: 'Philos',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    brand: 'Rancilio',
    model: 'Rocky',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 55,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 0, microns: 216 },
      { setting: 27.5, microns: 708 },
      { setting: 55, microns: 1199 },
    ]),
    settingRanges: {
      [BREW_METHOD_CATEGORIES.espresso]: { min: 0, max: 11 },
      [BREW_METHOD_CATEGORIES.stovetop]: { min: 10, max: 27 },
      [BREW_METHOD_CATEGORIES.pourOver]: { min: 13, max: 30 },
      [BREW_METHOD_CATEGORIES.batch]: { min: 7, max: 42 },
      [BREW_METHOD_CATEGORIES.immersion]: { min: 30, max: 55 },
      [BREW_METHOD_CATEGORIES.cold]: { min: 37, max: 55 },
    },
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    /** One machine, two badges - searching for either has to find it. */
    brand: 'Sage / Breville',
    model: 'Smart Grinder Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 60,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 130 },
      { setting: 30.5, microns: 584 },
      { setting: 60, microns: 1039 },
    ]),
    settingRanges: {
      [BREW_METHOD_CATEGORIES.espresso]: { min: 1, max: 18 },
      [BREW_METHOD_CATEGORIES.stovetop]: { min: 17, max: 44 },
      [BREW_METHOD_CATEGORIES.pourOver]: { min: 21, max: 48 },
      [BREW_METHOD_CATEGORIES.batch]: { min: 11, max: 60 },
      [BREW_METHOD_CATEGORIES.immersion]: { min: 48, max: 60 },
      [BREW_METHOD_CATEGORIES.cold]: { min: 59, max: 60 },
    },
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Sage / Breville',
    model: 'Dose Control Pro',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 60,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 1, microns: 130 },
      { setting: 30.5, microns: 584 },
      { setting: 60, microns: 1039 },
    ]),
    settingRanges: {
      [BREW_METHOD_CATEGORIES.espresso]: { min: 1, max: 18 },
      [BREW_METHOD_CATEGORIES.stovetop]: { min: 17, max: 44 },
      [BREW_METHOD_CATEGORIES.pourOver]: { min: 21, max: 48 },
      [BREW_METHOD_CATEGORIES.batch]: { min: 11, max: 60 },
      [BREW_METHOD_CATEGORIES.immersion]: { min: 48, max: 60 },
      [BREW_METHOD_CATEGORIES.cold]: { min: 59, max: 60 },
    },
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Weber Workshops',
    model: 'Key',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Option-O',
    model: 'Lagom Mini',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Option-O',
    model: 'Lagom P100',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Ceado',
    model: 'E37S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Ceado',
    model: 'E37Z',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Ceado',
    model: 'Life',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    brand: 'Compak',
    model: 'E5',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Compak',
    model: 'E8',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Compak',
    model: 'K10',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    brand: 'Lelit',
    model: 'William PL72',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Lelit',
    model: 'Fred PL043MMI',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
];
