import { GRINDER_TYPICAL_USES, GRINDER_UNIT_TYPES } from '@brewmate/shared';

import type { GrinderSeed } from './grinderSeed.js';

/**
 * Electric grinders built around filter brewing.
 *
 * Their dials print numbers rather than counting clicks, and none of the
 * manufacturers publish a micron figure for them, so no curve is claimed.
 * A stepless dial is recorded with a step of zero.
 */
export const FILTER_GRINDER_SEEDS: readonly GrinderSeed[] = [
  {
    brand: 'Baratza',
    model: 'Encore',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Baratza',
    model: 'Encore ESP',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Virtuoso+',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Baratza',
    model: 'Vario',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Vario+',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Sette 270',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 31,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },

  {
    brand: 'Fellow',
    model: 'Ode Gen 1',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 11,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Fellow',
    model: 'Ode Gen 2',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 11,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Fellow',
    model: 'Opus',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 11,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Wilfa',
    model: 'Uniform',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Wilfa',
    model: 'Uniform+',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Wilfa',
    model: 'Svart',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },

  {
    brand: 'Mahlkönig',
    model: 'X54',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 1,
    maxSetting: 30,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mahlkönig',
    model: 'EK43',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 11,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Mahlkönig',
    model: 'EK43 S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 11,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Timemore',
    model: 'Sculptor 064',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Sculptor 078',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Sculptor 078S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Varia',
    model: 'VS3',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Varia',
    model: 'VS6',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 90,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
];
