import { GRINDER_TYPICAL_USES, GRINDER_UNIT_TYPES } from '@brewmate/shared';

import { estimatedCalibration } from './estimatedCalibration.js';
import type { GrinderSeed } from './grinderSeed.js';

/**
 * Hand grinders, which count in clicks from the burrs touching.
 *
 * A click means nothing on its own - 20 clicks is espresso on one grinder and
 * French press on another - so the only thing that makes two of them
 * comparable is the micron curve, and the curve is only present where the
 * manufacturer publishes a microns-per-click figure. Where it is absent, it is
 * absent on purpose: an invented number would be worse than none.
 */
export const HAND_GRINDER_SEEDS: readonly GrinderSeed[] = [
  {
    brand: 'Comandante',
    model: 'C40 MK3',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 50,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 8, microns: 240 },
      { setting: 20, microns: 600 },
      { setting: 40, microns: 1200 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Comandante',
    model: 'C40 MK4',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 50,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 8, microns: 240 },
      { setting: 20, microns: 600 },
      { setting: 40, microns: 1200 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: '1Zpresso',
    model: 'JX',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 10, microns: 250 },
      { setting: 24, microns: 600 },
      { setting: 48, microns: 1200 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: '1Zpresso',
    model: 'JX-Pro',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 16, microns: 200 },
      { setting: 48, microns: 600 },
      { setting: 88, microns: 1100 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'J-Max',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 23, microns: 200 },
      { setting: 45, microns: 400 },
      { setting: 68, microns: 600 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: '1Zpresso',
    model: 'JE-Plus',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: '1Zpresso',
    model: 'K-Plus',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 9, microns: 200 },
      { setting: 27, microns: 600 },
      { setting: 54, microns: 1200 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'K-Max',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 9, microns: 200 },
      { setting: 27, microns: 600 },
      { setting: 54, microns: 1200 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'K-Ultra',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'X-Pro',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: estimatedCalibration([
      { setting: 16, microns: 200 },
      { setting: 48, microns: 600 },
      { setting: 88, microns: 1100 },
    ]),
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: '1Zpresso',
    model: 'Q2',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: '1Zpresso',
    model: 'ZP6',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: '1Zpresso',
    model: 'J-Ultra',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Timemore',
    model: 'Chestnut C2',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C3 ESP',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut X-Lite',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut Slim',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut S3',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },

  {
    brand: 'Kingrinder',
    model: 'K1',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'K2',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'K4',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'K6',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'P2',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },

  {
    brand: 'Hario',
    model: 'Skerton Pro',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Hario',
    model: 'Mini Mill Slim',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 24,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },

  {
    brand: 'Porlex',
    model: 'Mini',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 24,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Porlex',
    model: 'Tall',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 24,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },

  {
    /** Stepless: the dial is numbered, but it stops nowhere in particular. */
    brand: 'Kinu',
    model: 'M47',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 0,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Knock',
    model: 'Feldgrind',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 80,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Knock',
    model: 'Aergrind',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 80,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },

  {
    brand: 'Normcore',
    model: 'Hand Grinder V2',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
];
