import { GRINDER_TYPICAL_USES, GRINDER_UNIT_TYPES } from '@brewmate/shared';

import type { GrinderSeed } from './grinderSeed.js';

/**
 * Grinders sold on the Czech and Slovak market that no grind-size chart covers.
 *
 * The catalogue's other lists come from charts written by people who brew;
 * these come from a shop, which means they are the grinders somebody in
 * Bratislava or Brno actually walks out with. A Nuttii or an AVX will never
 * appear in an English grind chart and its owner still has to find it in the
 * picker.
 *
 * What a shop listing can and cannot say shaped this list hard:
 *
 * - `minSetting`, `maxSetting` and `step` come from one stated figure, the
 *   number of grind positions the collar has. Zero to that number, one step
 *   apart. Nothing else about the collar is published, so nothing else is
 *   claimed.
 * - `typicalUse` comes from the shop's own espresso/filter field.
 * - There is no `micronCalibration` and no `settingRanges` for any of them.
 *   A shop says how many positions a collar has; it does not say what any of
 *   them grind to, and it never says which one to use for a V60. These entries
 *   therefore answer "is my grinder in here" and nothing more - the grind
 *   guidance falls back to the method window and gives them a grind in words.
 *
 * Every grinder whose listing stated no position count at all was left out
 * rather than given a plausible-looking range. That mistake is already in this
 * repository's history: twenty-one entries once shared a collar of 0-90
 * because somebody needed a number, and they read as measurements until the
 * day somebody checked.
 */
export const SHOP_GRINDER_SEEDS: readonly GrinderSeed[] = [
  {
    brand: '1Zpresso',
    model: 'ZP6 S',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'AeroPress Inc.',
    model: 'Manual',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'AVX',
    model: 'CG1',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 31,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'AVX',
    model: 'CG5',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 31,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'AVX',
    model: 'EG001',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Baratza',
    model: 'Sette 270Wi',
    unitType: GRINDER_UNIT_TYPES.numbers,
    /**
     * The shop says 270 positions and it is right, but that is the count of
     * macro and micro combinations rather than the numbers on the collar - the
     * Sette's macro ring is marked 1 to 31, exactly as its sibling here
     * records. Taken from the sibling, because the two share the mechanism and
     * differ in having a scale built in.
     */
    minSetting: 1,
    maxSetting: 31,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Baratza',
    model: 'Sette 30 AP',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 30,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Barista&Co',
    model: 'Core All Grind Plus',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Femobook',
    model: 'A2 Electric',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 120,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Gaggia',
    model: 'MD15',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 15,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Hario',
    model: 'PRO',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 90,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Kingrinder',
    model: 'K7',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 125,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Mahlkönig',
    model: 'X54 HOME',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Muvna',
    model: 'Electric Grinder',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 100,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Nuttii',
    model: 'OX LITE',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 16,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Nuttii',
    model: 'OX PRO',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 16,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Nuttii',
    model: 'Panacle G1S',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 24,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Nuttii',
    model: 'Panacle Goose Serie',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 24,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Outin',
    model: 'Fino',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 28,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'OXO',
    model: 'Brew Manual',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 40,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Sage',
    model: 'BCG820BTR AUTOMATIC',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Tiamo',
    model: 'S.S.',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 12,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Timemore',
    model: 'BRICKS 01S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 150,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C5 ESP PRO',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 50,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut C5 PRO',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 48,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.espresso,
  },
  {
    brand: 'Timemore',
    model: 'Chestnut G1',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'Timemore',
    model: 'Millab E01',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 60,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Nano 3',
    unitType: GRINDER_UNIT_TYPES.clicks,
    minSetting: 0,
    maxSetting: 20,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Timemore',
    model: 'Whirly 01S',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 50,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
  {
    brand: 'Wilfa',
    model: 'Balance CG1B-275',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 31,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.filter,
  },
  {
    brand: 'ZeroHero',
    model: 'RUI Mini',
    unitType: GRINDER_UNIT_TYPES.numbers,
    minSetting: 0,
    maxSetting: 36,
    step: 1,
    micronCalibration: null,
    settingRanges: null,
    typicalUse: GRINDER_TYPICAL_USES.both,
  },
];
