export { authPlugin } from './authPlugin.js';
export type { AuthPluginOptions } from './authPlugin.js';
export { createFirebaseApp } from './firebaseApp.js';
export { FIREBASE_AUTH_ERROR_CODES, readErrorCode } from './firebaseAuthErrorCodes.js';
export { createFirebaseIdentityDeleter } from './firebaseIdentityDeleter.js';
export { createFirebaseTokenVerifier } from './firebaseTokenVerifier.js';
export { extractBearerToken } from './extractBearerToken.js';
export type { IdentityDeleter } from './identityDeleter.js';
export { requireCurrentUser } from './requireCurrentUser.js';
export type { TokenVerifier } from './tokenVerifier.js';
export type { VerifiedToken } from './verifiedToken.js';
